---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-redmine
    spec:      
      containers:
      - image: redmine:4.1.1
        name: my-redmine 
        ports:
        - containerPort: 3000       
        env:
        - name: REDMINE_DB_POSTGRES
          value: database
        - name: REDMINE_DB_USERNAME
          value: testuser          
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: REDMINE_DB_DATABASE
          value: testdatabase
        - name: REDMINE_SECRET_KEY_BASE 
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: REDMINE_SECRET_KEY_BASE
