FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt 
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8080

FROM scratch

COPY --from= /app.py

CMD [ "python3", "app.py" ]
